# Generated by Django 5.1.9 on 2025-05-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cel',
            fields=[
                ('az', models.IntegerField(primary_key=True, serialize=False, verbose_name='Azonosító')),
                ('megnevezes', models.CharField(max_length=255, verbose_name='Megnevezés')),
                ('civil', models.BooleanField(verbose_name='Civil összefogás')),
            ],
            options={
                'verbose_name': 'Cél',
                'verbose_name_plural': 'Célok',
            },
        ),
        migrations.CreateModel(
            name='Felajanlas',
            fields=[
                ('az', models.AutoField(primary_key=True, serialize=False, verbose_name='Azonosító')),
                ('datum', models.DateField(verbose_name='Dátum')),
                ('szamlaaz', models.IntegerField(verbose_name='Számla azonosító')),
                ('osszeg', models.IntegerField(verbose_name='Összeg')),
                ('celaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='felajanlasok', to='felajanlasok.cel', verbose_name='Cél')),
            ],
            options={
                'verbose_name': 'Felajánlás',
                'verbose_name_plural': 'Felajánlások',
                'ordering': ['datum', 'szamlaaz'],
            },
        ),
    ]
